### ISSUE TITLE
Update backend tests

### ISSUE THREAD

**Issue by funkydrummer** [opacity/storage-node#178]

**Comment by rfornea** [comment]
We should also add tests for a few files that still don't have them.  

Also, /upload and /init-upload endpoints now take form data instead of json requests. This has broken the unit tests for those endpoints and also /delete (which utilizes the /upload endpoint test helper method to create a file that it can delete, although we could also change this so it doesn't depend on that helper method anymore). We need to update the tests to create form requests instead.  

Remove all t.Skip() calls.
